carrinho/urls.py
from django.urls import path
from . import views

app_name = 'carrinho'

urlpatterns = [
    path('', views.detalhes_carrinho, name='detalhes_carrinho'),
    path('adicionar/<int:id_produto>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover/<int:id_produto>/', views.remover_do_carrinho, name='remover_do_carrinho'),
]

lojavirtual/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('produtos/', include('produtos.urls', namespace='produtos')),
    path('carrinho/', include('carrinho.urls', namespace='carrinho')),
    path('pedidos/', include('pedidos.urls', namespace='pedidos')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import index, sobre, contato


urlpatterns = [
    path('', index, name='index'),
    path('sobre/', sobre, name='sobre'),
    path('contato/', contato, name='contato')
]

pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path('criar/', views.criar_pedido, name='criar_pedido')
]

produtos/urls.py
from django.urls import path
from .views import listar_produtos, detalhar_produto

app_name = 'produtos'

urlpatterns = [
    path('<str:id_produto>/<slug_produto>/', detalhar_produto, name='detalhes_produto'),
    path('<slug_categoria>/', listar_produtos, name='listar_produtos_por_categoria'),
    path('', listar_produtos, name='listar_produtos'),
]

carrinho/models.py
from django.db import models

# Create your models here.

carrinho/forms.py
from django import forms

OPCOES_QUANTIDADE_PRODUTO = []

for i in range(1, 11):
    OPCOES_QUANTIDADE_PRODUTO.append((i, str(i)))


class FormAdicionarProdutoAoCarrinho(forms.Form):

    quantidade = forms.TypedChoiceField(
        choices=OPCOES_QUANTIDADE_PRODUTO, coerce=int)

    atualizar = forms.BooleanField(required=False, widget=forms.HiddenInput)

carrinho/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from produtos.models import Produto
from .carrinho import Carrinho
from .forms import FormAdicionarProdutoAoCarrinho


@require_POST
def adicionar_ao_carrinho(request, id_produto):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=id_produto)
    form = FormAdicionarProdutoAoCarrinho(request.POST)
    if form.is_valid():
        dados = form.cleaned_data
        carrinho.adicionar(
            produto=produto,
            quantidade=dados['quantidade'],
            atualizar_quantidade=dados['atualizar'])
    return redirect('carrinho:detalhes_carrinho')


def remover_do_carrinho(request, id_produto):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=id_produto)
    carrinho.remover(produto)
    return redirect('carrinho:detalhes_carrinho')


def detalhes_carrinho(request):
    carrinho = Carrinho(request)
    for item in carrinho:
        item['formulario_adicionar_produto_ao_carrinho'] = \
            FormAdicionarProdutoAoCarrinho(
                initial={'quantidade': item['quantidade'], 'atualizar': True})
    return render(request, 'carrinho/detalhes_carrinho.html', {'carrinho': carrinho})

templates/carrinho/detalhes_carrinho.html
{% extends "base.html" %}
{% block conteudo %}
{% if carrinho|length == 0 %}
<h2>Seu Carrinho está vazio!</h2>
<a href="{% url 'produtos:listar_produtos' %}">Comprar</a>
{% else %}
<h2>Seu Carrinho de Compras:</h2>
<table>
    <thead>
        <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Remover</th>
            <th>Preço unitário</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
    {% for item in carrinho %}
        {% with produto=item.produto %}
        <tr>
            <td>{{ produto.nome }}</td>
            <td>
                <form action="{% url 'carrinho:adicionar_ao_carrinho' produto.id %}" method = "post">
                {% csrf_token %}
                    {{ item.formulario_adicionar_produto_ao_carrinho.quantidade }}
                    {{ item.formulario_adicionar_produto_ao_carrinho.atualizar }}
                    <input type="submit" value="Atualizar">
                </form>
            </td>
            <td>
                <a href="{% url 'carrinho:remover_do_carrinho' produto.id %}">Remover</a>
            </td>
            <td>R$ {{ item.preco }}</td>
            <td>R$ {{ item.subtotal }}</td>
        </tr>
        {% endwith %}
    {% endfor %}
    <tr>
        <td><b>Total: R$ {{ carrinho.get_total_geral }}</b></td>

    </tr>
    </tbody>
</table>
<a href="{% url 'produtos:listar_produtos' %}">Comprar mais produtos</a>
<a href="{% url 'pedidos:criar_pedido' %}"> Finalizar</a>
{% endif %}
{% endblock %}