carrinho/urls.py
from django.urls import path
from . import views

app_name = 'carrinho'

urlpatterns = [
    path('', views.detalhes_carrinho, name='detalhes_carrinho'),
    path('adicionar/<int:id_produto>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover/<int:id_produto>/', views.remover_do_carrinho, name='remover_do_carrinho'),
]

lojavirtual/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('produtos/', include('produtos.urls', namespace='produtos')),
    path('carrinho/', include('carrinho.urls', namespace='carrinho')),
    path('pedidos/', include('pedidos.urls', namespace='pedidos')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import index, sobre, contato


urlpatterns = [
    path('', index, name='index'),
    path('sobre/', sobre, name='sobre'),
    path('contato/', contato, name='contato')
]

templates/barra_navegacao.html
<nav>
    <div class="tudo">
        <div class="container">
            <a href="/">Página Principal</a>
            <a href="/produtos">Produtos</a>
            <a href="/contato">Entre em contato</a>
            <a href="/sobre">Sobre nós</a>
        </div>
        <div class="container">
            {% if not user.is_anonymous %}
                <ul class="linksAdm">
                    <li><a href="/admin/auth/user/">Usuários</a></li>
                    <li><a href="/admin/produtos/produto/">Produtos</a></li>
                    <li><a href="/admin/produtos/categoria/">Categoria</a></li>
                    <li><a href="/admin/pedidos/pedido/">Pedidos</a></li>
                </ul>
            {% endif %}
            <div class="teste">
                {% if user.is_anonymous %}
                    <p class="login-desc">Crie sua conta ou faça login {{ user.get_name }}</p>
                    <div class="inputs">
                        <a href="{% url 'login' %}" class="login">Login</a>
                        <a href="{% url 'signup' %}" class="criar_conta">Criar conta</a>
                    </div>
                {% else %}
            </div>
        </div>
    </div>
            <div class="naosei">
                <h3 class="boasVindas">Seja bem vindo(a) {{ user.username }}</h3>
                <a href="{% url 'logout' %}">Logout</a>
                <h3 class="username">{{ user.username }}</h3>
            {% endif %}
            </div>
    <h4>{% with quantidade_itens=carrinho|length %}
        {% if not user.is_anonymous %}
            {% if quantidade_itens > 0 %}
            Seu carrinho de compras:
            <a href="{% url 'carrinho:detalhes_carrinho' %}">{{ quantidade_itens }}
                produto{{ quantidade_itens|pluralize }} - R${{ carrinho.get_total_geral }}</a>
            {% else %}
            <p class="car_vazio">Seu carrinho está vazio.</p>
            {% endif %}
        {% endif %}
        {% endwith %}
    </h4>
</nav>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Projeto Django</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    {% include 'barra_navegacao.html' %}
    <div class="container-fluid">
        {% block conteudo %}
        {% endblock conteudo %}
    </div>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>